<!DOCTYPE html>
<html lang="id">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="Keranjang belanja SHOP.CO.">
        <title>Keranjang Belanja | SHOP.CO</title>
        @vite(['resources/css/app.css', 'resources/js/app.js'])
    </head>
    <body class="bg-white font-sans text-zinc-950 antialiased">
        <div class="bg-black px-5 py-2 text-center text-xs text-white sm:text-sm">Gratis ongkir untuk pesanan pertama Anda. <a class="ml-1 underline underline-offset-2" href="{{ route('home') }}#produk">Belanja sekarang</a></div>
        <header class="border-b border-zinc-200 bg-white">
            <div class="mx-auto flex max-w-7xl items-center justify-between gap-5 px-5 py-5 lg:px-8">
                <a class="text-2xl font-black tracking-[-0.08em] sm:text-3xl" href="{{ route('home') }}">SHOP.CO</a>
                <nav class="hidden items-center gap-7 text-sm font-medium lg:flex" aria-label="Navigasi utama"><a href="{{ route('home') }}">Beranda</a><a href="{{ route('home') }}#produk">Produk</a><a href="{{ route('home') }}#kategori">Kategori</a></nav>
                <form class="hidden max-w-sm flex-1 md:block" role="search"><label class="sr-only" for="product-search">Cari produk</label><div class="flex items-center gap-2 rounded-full bg-zinc-100 px-4 py-2.5 text-zinc-500"><svg class="size-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><circle cx="11" cy="11" r="6"/><path d="m20 20-4-4"/></svg><input id="product-search" class="w-full bg-transparent text-sm outline-none placeholder:text-zinc-400" type="search" placeholder="Cari produk..."></div></form>
                <div class="flex items-center gap-2"><a class="rounded-full bg-zinc-100 p-3" href="{{ route('cart') }}" aria-label="Keranjang"><svg class="size-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M3 4h2l2.4 11.2a2 2 0 0 0 2 1.6h7.8a2 2 0 0 0 1.9-1.4L21 8H6"/><circle cx="10" cy="20" r="1"/><circle cx="18" cy="20" r="1"/></svg></a><a class="hidden rounded-full px-4 py-2.5 text-sm font-semibold hover:bg-zinc-100 sm:inline-block" href="{{ route('login') }}">Masuk</a><a class="rounded-full bg-black px-4 py-2.5 text-sm font-semibold text-white hover:bg-zinc-700" href="{{ route('register') }}">Daftar</a></div>
            </div>
        </header>

        <main class="mx-auto max-w-7xl px-5 py-8 lg:px-8 lg:py-12">
            <nav class="flex items-center gap-2 text-sm text-zinc-500" aria-label="Breadcrumb"><a href="{{ route('home') }}" class="hover:text-black">Beranda</a><span aria-hidden="true">›</span><span class="text-zinc-950">Keranjang</span></nav>
            <h1 class="mt-8 text-4xl font-black tracking-[-0.06em] sm:text-5xl">KERANJANG ANDA</h1>
            <div class="mt-8 grid items-start gap-5 lg:grid-cols-[minmax(0,1.5fr)_minmax(330px,0.8fr)]">
                <section id="cart-items" class="rounded-3xl border border-zinc-200 px-5 sm:px-7" aria-label="Daftar produk di keranjang">
                    @foreach ([['Gradient Graphic T-shirt', 'Ukuran: L', 'Putih', 145000, 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=500&q=85'], ['Kemeja Linen Santai', 'Ukuran: M', 'Beige', 189000, 'https://images.unsplash.com/photo-1598032895397-b9472444bf93?auto=format&fit=crop&w=500&q=85'], ['Sneakers Harian', 'Ukuran: 42', 'Merah', 429000, 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=500&q=85']] as [$name, $size, $color, $price, $image])
                        <article class="cart-item flex gap-4 border-b border-zinc-200 py-5 last:border-0 sm:gap-5" data-price="{{ $price }}"><img class="size-24 shrink-0 rounded-2xl bg-[#f0eeed] object-cover sm:size-32" src="{{ $image }}" alt="{{ $name }}"><div class="flex min-w-0 flex-1 flex-col"><div class="flex items-start justify-between gap-3"><div><h2 class="text-base font-bold sm:text-lg">{{ $name }}</h2><p class="mt-1 text-xs text-zinc-600">{{ $size }}</p><p class="mt-1 text-xs text-zinc-600">Warna: {{ $color }}</p></div><button class="remove-cart-item p-1 text-red-500 transition hover:text-red-700" type="button" aria-label="Hapus {{ $name }}"><svg class="size-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 7h16M10 11v6M14 11v6M6 7l1 13h10l1-13M9 7V4h6v3"/></svg></button></div><div class="mt-auto flex items-end justify-between gap-3 pt-4"><p class="text-lg font-bold sm:text-xl">Rp{{ number_format($price, 0, ',', '.') }}</p><div class="flex items-center gap-4 rounded-full bg-zinc-100 px-4 py-2"><button class="cart-quantity text-xl leading-none" data-action="decrease" type="button" aria-label="Kurangi jumlah">−</button><span class="item-quantity min-w-4 text-center text-sm">1</span><button class="cart-quantity text-xl leading-none" data-action="increase" type="button" aria-label="Tambah jumlah">+</button></div></div></div></article>
                    @endforeach
                    <p id="empty-cart" class="hidden py-16 text-center text-zinc-500">Keranjang Anda masih kosong.</p>
                </section>
                <aside class="rounded-3xl border border-zinc-200 p-6 sm:p-7"><h2 class="text-2xl font-bold">Ringkasan Pesanan</h2><dl class="mt-7 space-y-5 text-sm"><div class="flex justify-between gap-4 text-zinc-600"><dt>Subtotal</dt><dd id="cart-subtotal" class="font-bold text-zinc-950">Rp763.000</dd></div><div class="flex justify-between gap-4 text-zinc-600"><dt>Diskon <span class="text-zinc-400">(-10%)</span></dt><dd id="cart-discount" class="font-bold text-red-500">-Rp76.300</dd></div><div class="flex justify-between gap-4 text-zinc-600"><dt>Biaya pengiriman</dt><dd class="font-bold text-zinc-950">Gratis</dd></div></dl><div class="my-6 h-px bg-zinc-200"></div><div class="flex justify-between gap-4 text-lg"><span>Total</span><strong id="cart-total">Rp686.700</strong></div><div class="mt-6 flex gap-2"><label class="flex flex-1 items-center gap-2 rounded-full bg-zinc-100 px-4 py-3 text-sm text-zinc-400"><span aria-hidden="true">%</span><span class="sr-only">Kode promo</span><input class="w-full bg-transparent outline-none placeholder:text-zinc-400" type="text" placeholder="Tambah kode promo"></label><button class="rounded-full bg-black px-5 text-sm font-semibold text-white hover:bg-zinc-700" type="button">Pakai</button></div><a class="mt-4 flex items-center justify-center gap-2 rounded-full bg-black px-5 py-4 text-sm font-semibold text-white transition hover:bg-zinc-700" href="{{ route('checkout') }}">Lanjut ke Checkout <span aria-hidden="true">→</span></a></aside>
            </div>
        </main>
        <footer class="mt-10 bg-[#f0f0f0]"><div class="mx-auto max-w-7xl px-5 py-10 text-sm text-zinc-500 lg:px-8"><div class="flex flex-col justify-between gap-5 border-b border-zinc-300 pb-8 sm:flex-row"><a class="text-2xl font-black tracking-[-0.08em] text-zinc-950" href="{{ route('home') }}">SHOP.CO</a><p>Marketplace pilihan untuk kebutuhan sehari-hari.</p></div><p class="pt-6 text-xs">SHOP.CO © {{ now()->year }}. Semua hak dilindungi.</p></div></footer>
    </body>
</html>
