<x-layouts.seller title="{{ $product->exists ? 'Ubah Produk' : 'Tambah Produk' }} | SHOP.CO" active="products">
    <div class="mx-auto max-w-2xl"><h1 class="text-4xl font-black">{{ $product->exists ? 'UBAH PRODUK' : 'TAMBAH PRODUK' }}</h1><form class="mt-8 space-y-5" method="POST" action="{{ $product->exists ? route('seller.products.update', $product) : route('seller.products.store') }}" enctype="multipart/form-data">@csrf @if($product->exists) @method('PUT') @endif
        <label class="block text-sm font-semibold">Nama<input class="mt-2 w-full rounded-xl border border-zinc-200 p-3" name="name" value="{{ old('name', $product->name) }}" required></label>
        <label class="block text-sm font-semibold">Kategori<select class="mt-2 w-full rounded-xl border border-zinc-200 p-3" name="category_id"><option value="">Tanpa kategori</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('category_id', $product->category_id) == $category->id)>{{ $category->name }}</option>@endforeach</select></label>
        <div class="grid gap-5 sm:grid-cols-2"><label class="block text-sm font-semibold">Harga<input class="mt-2 w-full rounded-xl border border-zinc-200 p-3" type="number" min="0" name="price" value="{{ old('price', $product->price) }}" required></label><label class="block text-sm font-semibold">Stok<input class="mt-2 w-full rounded-xl border border-zinc-200 p-3" type="number" min="0" name="stock" value="{{ old('stock', $product->stock) }}" required></label></div>
        <label class="block text-sm font-semibold">Status<select class="mt-2 w-full rounded-xl border border-zinc-200 p-3" name="status"><option value="tersedia" @selected(old('status', $product->status ?: 'tersedia') === 'tersedia')>Tersedia</option><option value="habis" @selected(old('status', $product->status) === 'habis')>Habis</option></select></label>
        <label class="block text-sm font-semibold">Deskripsi<textarea class="mt-2 w-full rounded-xl border border-zinc-200 p-3" name="description" rows="5">{{ old('description', $product->description) }}</textarea></label><label class="block text-sm font-semibold">Gambar<input class="mt-2 block w-full rounded-xl border border-zinc-200 p-3" type="file" name="image" accept="image/*"></label><button class="rounded-full bg-black px-6 py-3 text-sm font-bold text-white" type="submit">Simpan Produk</button>
    </form></div>
</x-layouts.seller>
