<!DOCTYPE html>
<html lang="id">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Checkout | SHOP.CO</title>
        @vite(['resources/css/app.css', 'resources/js/app.js'])
    </head>
    <body class="bg-white font-sans text-zinc-950 antialiased">
        <x-storefront-header />
        <main class="mx-auto max-w-7xl px-5 py-8 lg:px-8 lg:py-12"><h1 class="text-4xl font-black tracking-[-0.06em] sm:text-5xl">CHECKOUT</h1>
            @if ($errors->any()) <div class="mt-5 rounded-xl bg-red-50 p-4 text-sm text-red-800">{{ $errors->first() }}</div> @endif
            <form class="mt-8 grid items-start gap-5 lg:grid-cols-[minmax(0,1.5fr)_minmax(330px,0.8fr)]" method="POST" action="{{ route('checkout.store') }}">@csrf
                <section class="rounded-3xl border border-zinc-200 p-6 sm:p-8"><h2 class="text-2xl font-bold">Alamat Pengiriman</h2>@if ($addresses->isNotEmpty())<label class="mt-6 block text-sm font-semibold" for="address_id">Pilih alamat tersimpan</label><select class="checkout-input mt-2" id="address_id" name="address_id"><option value="">Gunakan alamat baru</option>@foreach ($addresses as $address)<option value="{{ $address->id }}">{{ $address->recipient_name }} · {{ $address->city }}{{ $address->is_default ? ' (Utama)' : '' }}</option>@endforeach</select>@endif<div class="mt-6 grid gap-5 sm:grid-cols-2"><div><label class="mb-2 block text-sm font-semibold" for="recipient_name">Nama lengkap</label><input class="checkout-input" id="recipient_name" name="recipient_name" value="{{ old('recipient_name', auth()->user()->name) }}"></div><div><label class="mb-2 block text-sm font-semibold" for="phone">Nomor telepon</label><input class="checkout-input" id="phone" name="phone" value="{{ old('phone') }}"></div><div class="sm:col-span-2"><label class="mb-2 block text-sm font-semibold" for="address">Alamat lengkap</label><textarea class="checkout-input min-h-28 resize-none rounded-2xl" id="address" name="address">{{ old('address') }}</textarea></div><div><label class="mb-2 block text-sm font-semibold" for="city">Kota</label><input class="checkout-input" id="city" name="city" value="{{ old('city') }}"></div><div><label class="mb-2 block text-sm font-semibold" for="postal_code">Kode pos</label><input class="checkout-input" id="postal_code" name="postal_code" value="{{ old('postal_code') }}"></div></div><section class="mt-5 rounded-3xl border border-zinc-200 p-6 sm:p-8"><h2 class="text-2xl font-bold">Metode Pembayaran</h2><p class="mt-2 text-sm text-zinc-500">Pembayaran dapat dikonfirmasi setelah pesanan dibuat.</p><label class="mt-5 flex items-center gap-3 rounded-2xl border-2 border-black bg-zinc-50 p-4 text-sm font-semibold"><input type="radio" name="payment" value="transfer" checked> Transfer bank</label></section></section>
                <aside class="rounded-3xl border border-zinc-200 p-6 sm:p-7 lg:sticky lg:top-6"><h2 class="text-2xl font-bold">Ringkasan Pesanan</h2><div class="mt-6 space-y-3 border-b border-zinc-200 pb-6">@foreach ($cart->items as $item)<div class="flex justify-between gap-4 text-sm text-zinc-600"><span>{{ $item->product->name }} × {{ $item->quantity }}</span><span class="font-semibold text-zinc-950">Rp{{ number_format($item->quantity * $item->product->price, 0, ',', '.') }}</span></div>@endforeach</div><div class="flex justify-between gap-4 pt-5 text-lg"><span>Total</span><strong>Rp{{ number_format($subtotal, 0, ',', '.') }}</strong></div><button class="mt-7 flex w-full items-center justify-center rounded-full bg-black px-5 py-4 text-sm font-bold text-white" type="submit">Buat Pesanan <span class="ml-2">→</span></button><p class="mt-4 text-center text-xs text-zinc-500">Stok dikunci dan diverifikasi saat pesanan dibuat.</p></aside>
            </form>
        </main>
    </body>
</html>
