<!DOCTYPE html>
<html lang="id">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="Checkout pesanan SHOP.CO.">
        <title>Checkout | SHOP.CO</title>
        @vite(['resources/css/app.css', 'resources/js/app.js'])
    </head>
    <body class="bg-white font-sans text-zinc-950 antialiased">
        <div class="bg-black px-5 py-2 text-center text-xs text-white sm:text-sm">Gratis ongkir untuk pesanan pertama Anda. <a class="ml-1 underline underline-offset-2" href="{{ route('home') }}#produk">Belanja sekarang</a></div>
        <header class="border-b border-zinc-200 bg-white"><div class="mx-auto flex max-w-7xl items-center justify-between gap-5 px-5 py-5 lg:px-8"><a class="text-2xl font-black tracking-[-0.08em] sm:text-3xl" href="{{ route('home') }}">SHOP.CO</a><nav class="hidden items-center gap-7 text-sm font-medium lg:flex" aria-label="Navigasi utama"><a href="{{ route('home') }}">Beranda</a><a href="{{ route('home') }}#produk">Produk</a><a href="{{ route('home') }}#kategori">Kategori</a></nav><form class="hidden max-w-sm flex-1 md:block" role="search"><label class="sr-only" for="product-search">Cari produk</label><div class="flex items-center gap-2 rounded-full bg-zinc-100 px-4 py-2.5 text-zinc-500"><svg class="size-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><circle cx="11" cy="11" r="6"/><path d="m20 20-4-4"/></svg><input id="product-search" class="w-full bg-transparent text-sm outline-none placeholder:text-zinc-400" type="search" placeholder="Cari produk..."></div></form><div class="flex items-center gap-2"><a class="rounded-full bg-zinc-100 p-3" href="{{ route('cart') }}" aria-label="Kembali ke keranjang"><svg class="size-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M3 4h2l2.4 11.2a2 2 0 0 0 2 1.6h7.8a2 2 0 0 0 1.9-1.4L21 8H6"/><circle cx="10" cy="20" r="1"/><circle cx="18" cy="20" r="1"/></svg></a><a class="hidden rounded-full px-4 py-2.5 text-sm font-semibold hover:bg-zinc-100 sm:inline-block" href="{{ route('login') }}">Masuk</a><a class="rounded-full bg-black px-4 py-2.5 text-sm font-semibold text-white hover:bg-zinc-700" href="{{ route('register') }}">Daftar</a></div></div></header>

        <main class="mx-auto max-w-7xl px-5 py-8 lg:px-8 lg:py-12"><nav class="flex items-center gap-2 text-sm text-zinc-500" aria-label="Breadcrumb"><a href="{{ route('home') }}" class="hover:text-black">Beranda</a><span>›</span><a href="{{ route('cart') }}" class="hover:text-black">Keranjang</a><span>›</span><span class="text-zinc-950">Checkout</span></nav><h1 class="mt-8 text-4xl font-black tracking-[-0.06em] sm:text-5xl">CHECKOUT</h1>
            <div class="mt-8 grid items-start gap-5 lg:grid-cols-[minmax(0,1.5fr)_minmax(330px,0.8fr)]"><div class="space-y-5"><section class="rounded-3xl border border-zinc-200 p-6 sm:p-8"><div class="mb-7 flex items-center justify-between gap-4"><h2 class="text-2xl font-bold">Alamat Pengiriman</h2><span class="rounded-full bg-zinc-100 px-3 py-1 text-xs font-semibold">Langkah 1 dari 2</span></div><div class="grid gap-5 sm:grid-cols-2"><div><label class="mb-2 block text-sm font-semibold" for="recipient-name">Nama lengkap</label><input id="recipient-name" class="checkout-input" type="text" placeholder="Masukkan nama lengkap"></div><div><label class="mb-2 block text-sm font-semibold" for="recipient-phone">Nomor telepon</label><input id="recipient-phone" class="checkout-input" type="tel" placeholder="08xx-xxxx-xxxx"></div><div class="sm:col-span-2"><label class="mb-2 block text-sm font-semibold" for="recipient-address">Alamat lengkap</label><textarea id="recipient-address" class="checkout-input min-h-28 resize-none rounded-2xl" placeholder="Nama jalan, nomor rumah, RT/RW"></textarea></div><div><label class="mb-2 block text-sm font-semibold" for="recipient-city">Kota</label><input id="recipient-city" class="checkout-input" type="text" placeholder="Masukkan kota"></div><div><label class="mb-2 block text-sm font-semibold" for="recipient-postal">Kode pos</label><input id="recipient-postal" class="checkout-input" type="text" placeholder="Masukkan kode pos"></div></div></section><section class="rounded-3xl border border-zinc-200 p-6 sm:p-8"><h2 class="text-2xl font-bold">Metode Pembayaran</h2><p class="mt-2 text-sm text-zinc-500">Pilih metode pembayaran yang tersedia.</p><div class="mt-6 space-y-3"><label class="payment-option flex cursor-pointer items-center justify-between rounded-2xl border-2 border-black bg-zinc-50 p-4"><span class="flex items-center gap-3 text-sm font-semibold"><input class="payment-radio accent-black" name="payment" type="radio" value="transfer" checked> Transfer Bank</span><span class="text-xs text-zinc-500">BCA, BNI, Mandiri</span></label><label class="payment-option flex cursor-pointer items-center justify-between rounded-2xl border border-zinc-200 p-4"><span class="flex items-center gap-3 text-sm font-semibold"><input class="payment-radio accent-black" name="payment" type="radio" value="qris"> QRIS</span><span class="text-xs text-zinc-500">Bayar cepat & aman</span></label><label class="payment-option flex cursor-pointer items-center justify-between rounded-2xl border border-zinc-200 p-4"><span class="flex items-center gap-3 text-sm font-semibold"><input class="payment-radio accent-black" name="payment" type="radio" value="cod"> Bayar di tempat</span><span class="text-xs text-zinc-500">COD tersedia</span></label></div></section></div>
                <aside class="rounded-3xl border border-zinc-200 p-6 sm:p-7 lg:sticky lg:top-6"><h2 class="text-2xl font-bold">Ringkasan Pesanan</h2><div class="mt-6 space-y-4 border-b border-zinc-200 pb-6"><div class="flex justify-between gap-4 text-sm text-zinc-600"><span>3 produk</span><span class="font-semibold text-zinc-950">Rp763.000</span></div><div class="flex justify-between gap-4 text-sm text-zinc-600"><span>Diskon <span class="text-zinc-400">(-10%)</span></span><span class="font-semibold text-red-500">-Rp76.300</span></div><div class="flex justify-between gap-4 text-sm text-zinc-600"><span>Biaya pengiriman</span><span class="font-semibold text-zinc-950">Gratis</span></div></div><div class="flex justify-between gap-4 pt-5 text-lg"><span>Total</span><strong>Rp686.700</strong></div><button class="mt-7 flex w-full items-center justify-center gap-2 rounded-full bg-black px-5 py-4 text-sm font-bold text-white transition hover:bg-zinc-700" type="button">Buat Pesanan <span aria-hidden="true">→</span></button><p class="mt-4 text-center text-xs leading-5 text-zinc-500">Dengan melanjutkan, Anda menyetujui syarat dan ketentuan SHOP.CO.</p></aside>
            </div>
        </main>
        <footer class="mt-10 bg-[#f0f0f0]"><div class="mx-auto max-w-7xl px-5 py-10 text-sm text-zinc-500 lg:px-8"><div class="flex flex-col justify-between gap-5 border-b border-zinc-300 pb-8 sm:flex-row"><a class="text-2xl font-black tracking-[-0.08em] text-zinc-950" href="{{ route('home') }}">SHOP.CO</a><p>Marketplace pilihan untuk kebutuhan sehari-hari.</p></div><p class="pt-6 text-xs">SHOP.CO © {{ now()->year }}. Semua hak dilindungi.</p></div></footer>
    </body>
</html>
