<!DOCTYPE html>
<html lang="id">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="Detail produk Kemeja Linen Santai di SHOP.CO.">
        <title>Kemeja Linen Santai | SHOP.CO</title>
        @vite(['resources/css/app.css', 'resources/js/app.js'])
    </head>
    <body class="bg-white font-sans text-zinc-950 antialiased">
        <div class="bg-black px-5 py-2 text-center text-xs text-white sm:text-sm">Gratis ongkir untuk pesanan pertama Anda. <a class="ml-1 underline underline-offset-2" href="{{ route('home') }}#produk">Belanja sekarang</a></div>
        <header class="border-b border-zinc-200 bg-white">
            <div class="mx-auto flex max-w-7xl items-center justify-between gap-5 px-5 py-5 lg:px-8">
                <a class="text-2xl font-black tracking-[-0.08em] sm:text-3xl" href="{{ route('home') }}">SHOP.CO</a>
                <nav class="hidden items-center gap-7 text-sm font-medium lg:flex" aria-label="Navigasi utama"><a href="{{ route('home') }}">Beranda</a><a href="{{ route('home') }}#produk">Produk</a><a href="{{ route('home') }}#kategori">Kategori</a></nav>
                <form class="hidden max-w-sm flex-1 md:block" role="search"><label class="sr-only" for="product-search">Cari produk</label><div class="flex items-center gap-2 rounded-full bg-zinc-100 px-4 py-2.5 text-zinc-500"><svg class="size-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><circle cx="11" cy="11" r="6"/><path d="m20 20-4-4"/></svg><input id="product-search" class="w-full bg-transparent text-sm outline-none placeholder:text-zinc-400" type="search" placeholder="Cari produk..."></div></form>
                <div class="flex items-center gap-2 text-sm font-semibold"><a class="rounded-full px-4 py-2.5 hover:bg-zinc-100" href="{{ route('login') }}">Masuk</a><a class="rounded-full bg-black px-4 py-2.5 text-white hover:bg-zinc-700" href="{{ route('register') }}">Daftar</a></div>
            </div>
        </header>

        <main class="mx-auto max-w-7xl px-5 lg:px-8">
            <nav class="flex items-center gap-2 py-6 text-sm text-zinc-500" aria-label="Breadcrumb"><a href="{{ route('home') }}" class="hover:text-black">Beranda</a><span aria-hidden="true">›</span><a href="{{ route('home') }}#produk" class="hover:text-black">Produk</a><span aria-hidden="true">›</span><span class="text-zinc-900">Detail produk</span></nav>

            <section class="grid gap-8 pb-16 lg:grid-cols-[minmax(0,1.05fr)_minmax(360px,0.95fr)] lg:gap-12">
                <div class="grid gap-4 sm:grid-cols-[88px_minmax(0,1fr)]">
                    <div class="order-2 grid grid-cols-3 gap-3 sm:order-1 sm:grid-cols-1"><button class="product-thumb overflow-hidden rounded-2xl border-2 border-black bg-[#f0eeed]" data-image="0" type="button"><img class="aspect-square w-full object-cover" src="https://images.unsplash.com/photo-1598032895397-b9472444bf93?auto=format&fit=crop&w=600&q=85" alt="Kemeja linen tampak depan"></button><button class="product-thumb overflow-hidden rounded-2xl border-2 border-transparent bg-[#f0eeed]" data-image="1" type="button"><img class="aspect-square w-full object-cover" src="https://images.unsplash.com/photo-1596755389378-c31d21fd1273?auto=format&fit=crop&w=600&q=85" alt="Kemeja linen tampak samping"></button><button class="product-thumb overflow-hidden rounded-2xl border-2 border-transparent bg-[#f0eeed]" data-image="2" type="button"><img class="aspect-square w-full object-cover" src="https://images.unsplash.com/photo-1603252110481-7ba873bf42ab?auto=format&fit=crop&w=600&q=85" alt="Model memakai kemeja linen"></button></div>
                    <div class="order-1 overflow-hidden rounded-3xl bg-[#f0eeed] sm:order-2"><img id="product-image" class="aspect-square w-full object-cover" src="https://images.unsplash.com/photo-1598032895397-b9472444bf93?auto=format&fit=crop&w=1000&q=85" alt="Kemeja Linen Santai"></div>
                </div>
                <div class="flex flex-col justify-center">
                    <p class="text-xs font-bold uppercase tracking-[0.2em] text-zinc-500">Koleksi terbaru</p>
                    <h1 class="mt-3 text-4xl font-black leading-none tracking-[-0.06em] sm:text-5xl">KEMEJA LINEN SANTAI</h1>
                    <div class="mt-5 flex items-center gap-2"><span class="text-xl tracking-[0.12em] text-amber-400" aria-hidden="true">★★★★★</span><span class="text-sm text-zinc-600">4.8/5 <span class="text-zinc-400">(124 ulasan)</span></span></div>
                    <div class="mt-5 flex items-center gap-3"><span class="text-3xl font-bold">Rp189.000</span><span class="text-xl text-zinc-400 line-through">Rp229.000</span><span class="rounded-full bg-red-100 px-3 py-1 text-xs font-bold text-red-600">-18%</span></div>
                    <p class="mt-5 border-b border-zinc-200 pb-6 text-sm leading-6 text-zinc-600">Kemeja linen ringan dengan potongan relaxed yang nyaman dipakai sepanjang hari. Material adem, mudah dipadukan, dan dibuat oleh penjual lokal terpilih.</p>
                    <div class="border-b border-zinc-200 py-5"><p class="mb-3 text-sm text-zinc-500">Pilih warna</p><div class="flex gap-3"><button class="size-8 rounded-full border-2 border-black bg-[#ded4bd] ring-2 ring-white ring-offset-2 ring-offset-black" type="button" aria-label="Beige"></button><button class="size-8 rounded-full bg-[#243f3d]" type="button" aria-label="Hijau tua"></button><button class="size-8 rounded-full bg-[#30354e]" type="button" aria-label="Navy"></button></div></div>
                    <div class="border-b border-zinc-200 py-5"><p class="mb-3 text-sm text-zinc-500">Pilih ukuran</p><div class="flex flex-wrap gap-2"><button class="rounded-full bg-zinc-100 px-5 py-2.5 text-sm" type="button">S</button><button class="rounded-full bg-zinc-100 px-5 py-2.5 text-sm" type="button">M</button><button class="rounded-full bg-black px-5 py-2.5 text-sm text-white" type="button">L</button><button class="rounded-full bg-zinc-100 px-5 py-2.5 text-sm" type="button">XL</button></div></div>
                    <div class="mt-5 flex gap-3"><div class="flex items-center justify-between gap-5 rounded-full bg-zinc-100 px-4 py-3"><button class="quantity-button text-xl leading-none" data-action="decrease" type="button" aria-label="Kurangi jumlah">−</button><span id="quantity" class="min-w-5 text-center text-sm">1</span><button class="quantity-button text-xl leading-none" data-action="increase" type="button" aria-label="Tambah jumlah">+</button></div><a class="flex flex-1 items-center justify-center gap-2 rounded-full bg-black px-5 py-3 text-sm font-bold text-white transition hover:bg-zinc-700" href="{{ route('cart') }}">Tambah ke Keranjang <span aria-hidden="true">→</span></a></div>
                </div>
            </section>

            <section class="border-t border-zinc-200 py-10"><div class="grid grid-cols-3 border-b border-zinc-200 text-center text-sm"><button class="border-b-2 border-black pb-4 font-semibold" type="button">Detail Produk</button><button class="pb-4 text-zinc-500" type="button">Rating & Ulasan</button><button class="pb-4 text-zinc-500" type="button">FAQ</button></div><div class="mt-8 grid gap-5 text-sm leading-7 text-zinc-600 sm:grid-cols-2"><p>Terbuat dari linen premium yang terasa ringan dan breathable. Jahitan rapi dengan kerah klasik dan saku depan yang fungsional.</p><p>Produk dikemas dengan aman dan dikirim dari penjual lokal. Tersedia stok untuk ukuran S hingga XL.</p></div></section>

            <section class="py-10"><div class="mb-8 flex items-end justify-between"><h2 class="text-3xl font-black tracking-[-0.05em] sm:text-4xl">MUNGKIN ANDA SUKA</h2><a class="text-sm font-semibold underline underline-offset-4" href="{{ route('home') }}#produk">Lihat semua</a></div><div class="grid grid-cols-2 gap-4 sm:grid-cols-4">@foreach ([['Tas Kulit Esensial', 'Rp325.000', 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=85'], ['Sneakers Harian', 'Rp429.000', 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=85'], ['Jam Tangan Klasik', 'Rp279.000', 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=600&q=85'], ['Kaos Basic Premium', 'Rp149.000', 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=600&q=85']] as [$name, $price, $image])<article><a class="block overflow-hidden rounded-2xl bg-[#f0eeed]" href="{{ route('products.show', ['product' => 1]) }}"><img class="aspect-square w-full object-cover transition duration-500 hover:scale-105" src="{{ $image }}" alt="{{ $name }}"></a><h3 class="mt-3 text-sm font-bold">{{ $name }}</h3><div class="mt-1 text-xs text-amber-500">★★★★★ <span class="text-zinc-500">4.8/5</span></div><p class="mt-1 font-bold">{{ $price }}</p></article>@endforeach</div></section>
        </main>
        <footer class="mt-10 bg-[#f0f0f0]"><div class="mx-auto max-w-7xl px-5 py-10 text-sm text-zinc-500 lg:px-8"><div class="flex flex-col justify-between gap-5 border-b border-zinc-300 pb-8 sm:flex-row"><a class="text-2xl font-black tracking-[-0.08em] text-zinc-950" href="{{ route('home') }}">SHOP.CO</a><p>Marketplace pilihan untuk kebutuhan sehari-hari.</p></div><p class="pt-6 text-xs">SHOP.CO © {{ now()->year }}. Semua hak dilindungi.</p></div></footer>
    </body>
</html>
