<!DOCTYPE html>
<html lang="id">
    <head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{{ $order->order_number }} | SHOP.CO</title>@vite(['resources/css/app.css', 'resources/js/app.js'])</head>
    <body class="bg-white font-sans text-zinc-950 antialiased"><main class="mx-auto max-w-5xl px-5 py-10 lg:px-8"><a href="{{ route('orders.index') }}" class="text-sm text-zinc-500">← Riwayat pesanan</a><div class="mt-8 flex flex-wrap justify-between gap-4"><div><p class="text-sm text-zinc-500">Detail pesanan</p><h1 class="mt-1 text-4xl font-black">{{ $order->order_number }}</h1></div><span class="h-fit rounded-full bg-zinc-100 px-4 py-2 text-sm font-semibold">{{ str_replace('_', ' ', $order->status) }}</span></div>
        @if (session('success'))<p class="mt-5 rounded-xl bg-green-50 p-4 text-sm text-green-800">{{ session('success') }}</p>@endif @if ($errors->any())<p class="mt-5 rounded-xl bg-red-50 p-4 text-sm text-red-800">{{ $errors->first() }}</p>@endif
        <section class="mt-8 rounded-3xl border border-zinc-200 p-6"><h2 class="text-xl font-bold">Produk</h2><div class="mt-5 divide-y divide-zinc-200">@foreach ($order->items as $item)<div class="flex justify-between gap-4 py-4 text-sm"><span>{{ $item->product_name }} × {{ $item->quantity }}</span><strong>Rp{{ number_format($item->subtotal, 0, ',', '.') }}</strong></div>@endforeach</div><div class="mt-4 flex justify-between border-t border-zinc-200 pt-5 text-lg"><span>Total</span><strong>Rp{{ number_format($order->total_price, 0, ',', '.') }}</strong></div></section>
        <section class="mt-5 rounded-3xl border border-zinc-200 p-6"><h2 class="text-xl font-bold">Bukti pembayaran</h2>@if ($order->payment_proof)<p class="mt-3 text-sm text-zinc-600">Bukti pembayaran sudah diunggah.</p>@endif @if ($order->status === 'menunggu_bayar')<form class="mt-5 flex flex-wrap items-end gap-3" method="POST" action="{{ route('orders.payment-proof.store', $order) }}" enctype="multipart/form-data">@csrf<label class="text-sm font-semibold">Pilih gambar<input class="mt-2 block text-sm" type="file" name="payment_proof" accept="image/*" required></label><button class="rounded-full bg-black px-5 py-3 text-sm font-bold text-white" type="submit">Unggah bukti</button></form><p class="mt-3 text-xs text-zinc-500">JPG, PNG, atau WEBP, maksimal 5 MB.</p>@endif</section>
        <section class="mt-5 rounded-3xl border border-zinc-200 p-6"><h2 class="text-xl font-bold">Alamat pengiriman</h2><p class="mt-3 text-sm leading-6 text-zinc-600">{{ $order->recipient_name }} · {{ $order->phone }}<br>{{ $order->shipping_address }}, {{ $order->city }} {{ $order->postal_code }}</p></section>
    </main></body>
</html>
